version: '3.8'

services:

  jesse:
    # image: salehmir/jesse:0.21.3
    image: screoff/live_jesse:0.21.3
    depends_on:
      - db
    environment:
      ENV_DATABASES_POSTGRES_HOST: "db"
    ports:
      - 8888:8888
    volumes:
      - ./jesseData:/home
      - ./jesse_live:/jesse_live
      - ./jesse:/jesse-docker


  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: jesse_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jesse_db
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - 5432:5432
    volumes:
      - ./dbData:/var/lib/postgresql/data
