version: '3.8'

services:

  jesse:
    image: salehmir/jesse:0.18.2
    volumes:
      - ./jesseData:/home
    depends_on:
      - db
      - jesse-trades-info
    environment:
      ENV_DATABASES_POSTGRES_HOST: "db"
    ports:
      - 8888:8888

  jesse-trades-info:
    image: jessetradesinfo/jesse-trades-info:v0.2.0
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: jesse_db
      DB_USER: jesse_user
      DB_PASSWORD: password
      DB_PORT: 5432
    ports:
      - 3000:3000

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: jesse_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jesse_db
    ports:
      - 5432:5432
    volumes:
      - ./dbData:/var/lib/postgresql/data
